IR_Evaluation/app/ManualAssessment/models.py
class Assessment:
    def __init__(self, index_id, query_id, assessor, document, grade):
        self.index_id = index_id
        self.query_id = query_id
        self.assessor = assessor
        self.document = document
        self.grade = grade

    def get_index_id(self):
        return self.index_id

    def get_query_id(self):
        return self.query_id

    def get_assessor(self):
        return self.assessor

    def get_document(self):
        return self.document

    def get_grade(self):
        return self.grade

IR_Evaluation/app/ManualAssessment/controllers.py
from flask import Blueprint, render_template, request
from service import Service
from models import Assessment
from app.Utilities.Constants import RESULT_SIZE


# Define the blueprint: 'manual_assessment', set its url prefix: app.url/auth
manual_assessment = Blueprint('manual_assessment', __name__, url_prefix='/manual_assessment')


@manual_assessment.route('/', methods=['GET', 'POST'])
def assess():
    doc_list = []
    if request.method == 'POST':
        assessor = request.form['assessor']
        query_id = request.form['query_id']
        doc_retrieval_count = int(request.form['doc_count'])

        service = Service()
        doc_list = service.retrieve_documents(assessor, query_id, doc_retrieval_count)

    return render_template('ManualAssessment/manual_assessment.html', doc_list=doc_list)


@manual_assessment.route('/store', methods=['GET', 'POST'])
def store():
    request_type = request.form['button']
    if request_type == 'store_es':
        __store_to_es()
    else:
        __export_to_file()

    return render_template('ManualAssessment/manual_assessment.html', doc_list=[])


@manual_assessment.route('/store_results', methods=['GET', 'POST'])
def store_results():
    service = Service()
    service.store_results(RESULT_SIZE)
    return render_template('/index.html')


def __store_to_es():
    doc_size = int(request.form['doc_size']) + 1
    assessment_list = []

    for i in range(1, doc_size):
        index_id = request.form['index_id_' + str(i)]
        query_id = request.form['query_id_' + str(i)]
        assessor = request.form['assessor_' + str(i)]
        document = request.form['document_' + str(i)]
        grade = int(request.form['grade_' + str(i)])

        assessment = Assessment(index_id, query_id, assessor, document, grade)

        assessment_list.append(assessment)

    service = Service()
    service.store_assessment(assessment_list)


def __export_to_file():

    assessor = request.form['assessor_1'].split('_')[0]

    service = Service()
    service.export_assessment(assessor)

IR_Evaluation/app/TrecEvaluation/controller.py
from flask import Blueprint, render_template, request, jsonify

from app.Utilities.Constants import RESULTS_FILE
from service import Service

results_files = {'okapi_tf_results': 'okapi',
                 'tf_idf_results': 'tf_idf',
                 'bm25_results': 'bm25',
                 'laplace_uni_LM_results': 'laplace',
                 'jm_uni_lm_results': 'jm',
                 RESULTS_FILE: 'team',
                 'Trec-Text-long.txt': 'Test'}

qrel_files = {'qrels.adhoc.51-100.AP89.txt': 'trec_qrel',
              'qurel.1512.txt': 'team_qrel'}

# Define the blueprint: 'manual_assessment', set its url prefix: app.url/auth
trec_eval = Blueprint('trec_eval', __name__, url_prefix='/trec_eval')


@trec_eval.route('/', methods=['GET'])
def trec_evaluation():
    global results_files
    global qrel_files
    return render_template('TrecEvaluation/trec_eval.html',
                           results_files=results_files,
                           qrel_files=qrel_files,
                           evaluation={},
                           precision={},
                           recall={})


@trec_eval.route('/', methods=['GET', 'POST'])
def evaluate():
    global results_files
    global qrel_files

    qrel_file = request.form['qrel_file']
    results_file = request.form['results_file']
    show_query = False

    try:
        show_query = bool(request.form['show_query'])
    except:
        pass

    try:
        service = Service(qrel_file, results_file)
        evaluation = service.perform_evaluation(show_query)

        #array containing dictionary - query:[precision values]
        precision = service.get_precision()
        # array containing dictionary - query:[precision values]
        recall = service.get_recall()

        for key in precision:
            print key, ' - ', precision[key]

    except Exception as e:
        print type(e)
        return render_template('404.html'), 404

    return render_template('TrecEvaluation/trec_eval.html',
                           results_files=results_files,
                           qrel_files=qrel_files,
                           evaluation=evaluation,
                           precision=precision,
                           recall=recall)

IR_Evaluation/app/__init__.py
# Import flask and template operators
from flask import Flask, render_template

# Define the WSGI application object
app = Flask(__name__)


@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404


@app.route('/')
def home():
    return render_template('index.html')

# Import a module / component using its blueprint handler variable (mod_auth)
from app.ManualAssessment.controllers import manual_assessment
from app.TrecEvaluation.controller import trec_eval

# Register blueprint(s)
app.register_blueprint(manual_assessment)
app.register_blueprint(trec_eval)

IR_Evaluation/app/templates/ManualAssessment/manual_assessment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Manual Assessment</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../static/css/common.css">

</head>
<body>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title" align="center">
                Manual Assessment for Creating QRel
            </h3>
        </div>
        <div class="panel-body">
            <div class="raw">
                <form class="form-inline"
                        action="{{ url_for('manual_assessment.assess')}}"
                        method="post">
                    <div class="col-sm-3 form-group">
                        <label class="control-label">
                            Assessor
                        </label>
                        <select class="form-control" name="assessor">
                            <option>Tirthraj</option>
                            <option>Manthan</option>
                            <option>Shabbir</option>
                        </select>
                    </div>
                    <div class="col-sm-3 form-group">
                        <label class="control-label">
                            Query
                        </label>
                        <select class="form-control" name="query_id">
                            <option value="151201">picasso paintings</option>
                            <option value="151202">brancusi sculptures</option>
                            <option value="151203">barcelona gaudi architecture</option>
                        </select>
                    </div>
                    <div class="col-sm-4 form-group">
                        <label class="control-label">
                            Documents Count
                        </label>
                        <input class="form-control" name="doc_count" value="200" readonly/>
                    </div>
                    <div class="col-sm-2 form-group">
                        <button type="submit" class="btn btn-primary">Get Documents</button>
                    </div>
                </form>
            </div>
        </div>
        {% block body %}
            {% if doc_list|length >  0 %}
                <div class="raw">
                    <div class="col-sm-3 grade-doc-panel">
                        <div class="panel panel-primary new-background">
                        <div class="panel-heading" align="center">
                            <h3 class="panel-title">
                                Grade Documents
                            </h3>
                        </div>
                        <form class="form-horizontal"
                                        action="{{ url_for('manual_assessment.store')}}"
                                        method="post">
                            <input name="doc_size" value="{{ doc_list|length }}" hidden/>
                            <div class="panel-body doc-list-panel">
                                <div class="vertical-scroll">
                                    {% set i = 1 %}
                                    {% for doc in doc_list %}
                                    <input name="index_id_{{ i }}" value="{{ doc.index_id }}" hidden/>
                                    <input name="query_id_{{ i }}" value="{{ doc.query_id }}" hidden/>
                                    <input name="assessor_{{ i }}" value="{{ doc.assessor }}" hidden/>
                                    <div class="form-group bottom link-set">
                                        <input name="document_{{ i }}" value="{{ doc.document }}" hidden/>
                                        <div class="col-sm-6" align="center">
                                            <a class="url" href="#" data-value="{{ doc.document }}">{{ doc.index_id }}</a>
                                        </div>
                                        <div class="col-sm-6" align="center">
                                            {% set grade = doc.grade %}
                                            <select class="form-control" name="grade_{{ i }}">
                                                <option value="0" {% if grade=='0' %} selected="selected"{% endif %}>Non relevant</option>
                                                <option value="1" {% if grade=='1' %} selected="selected"{% endif %}>Relevant</option>
                                                <option value="2" {% if grade=='2' %} selected="selected"{% endif %}>Very relevant</option>
                                            </select>
                                        </div>
                                    </div>
                                    {% set i = i + 1 %}
                                            {% endfor %}
                                </div>
                            </div>
                            <div class="panel-footer submit-panel" align="center">
                                <button type="submit" class="btn btn-primary" name="button" value="store_es">Submit Assessment</button>
                                <button type="submit" class="btn btn-primary" name="button" value="export">Export</button>
                            </div>
                        </form>
                    </div>
                    </div>
                    <div class="col-sm-9 doc-view-panel">
                        <div class="panel panel-primary new-background">
                            <div class="panel-heading" align="center">
                                <h3 class="panel-title">
                                    <a id="url_address" href="#" target="_blank">Document Content</a>
                                </h3>
                            </div>
                            <div class="panel-body doc-list-panel view-vertical-scroll">
                                <iframe id="view_frame" src="" class="view-frame">
                                </iframe>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-2.2.4.min.js"
            integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
            integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
            crossorigin="anonymous"></script>
    <script src="../../static/js/ManualAssessment/doc_view.js"></script>
</body>
</html>

IR_Evaluation/app/templates/TrecEvaluation/trec_eval.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TREC Evaluation</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../static/css/common.css">

</head>
<body>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title" align="center">
                Perform TREC Evaluation
            </h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <form class="form-inline"
                        action="{{ url_for('trec_eval.evaluate')}}"
                        method="post">
                    <div class="col-sm-4 form-group">
                        <label class="control-label">
                            Results File to Evaluate
                        </label>
                        <select class="form-control set-qrel" name="results_file">
                            {% for key in results_files %}
                                <option value="{{ key }}">{{ results_files[key] }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-sm-4 form-group">
                        <label class="control-label">
                            Qrel File
                        </label>
                        <select class="form-control set-qrel" name="qrel_file">
                            {% for key in qrel_files %}
                                <option value="{{ key }}">{{ qrel_files[key] }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-sm-2 form-group">
                        <div class="checkbox form-control">
                            <label>
                              <input type="checkbox" name="show_query" value="True"> -q
                            </label>
                          </div>
                    </div>
                    <div class="col-sm-2 form-group">
                        <button type="submit" class="btn btn-primary form-control" name="evaluate">Evaluate</button>
                    </div>
                </form>
            </div>
        </div>

        {% if evaluation|length >  0 %}
            <div class="raw">
                <div class="col-sm-4 doc-view-panel">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title" align="center">
                                Evaluation
                            </h3>
                        </div>
                        <div class="panel-body">
                            <div class="eval-vertical-scroll">
                                {% for string in evaluation %}
                                    {{ string }}<br>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="panel-footer submit-panel" align="center">
                            <button id="draw_graph" type="submit" class="btn btn-primary">Draw Precision-Recall Curve</button>
                        </div>
                    </div>
                </div>
                <div class="col-sm-8 doc-view-panel">
                    <div class="panel panel-primary graph-panel">
                        <div class="panel-heading">
                            <h3 class="panel-title" align="center">
                                Graph
                            </h3>
                        </div>
                        <div class="panel-body .eval-vertical-scroll">
                            {% for key in precision %}
                                <div id="chart_div_{{ key }}" style="height: 400px;"></div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"
            integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
            crossorigin="anonymous"></script>
    <script src="../../static/js/amcharts.js" type="text/javascript"></script>
    <script src="../../static/js/serial.js" type="text/javascript"></script>
    <script src="https://www.amcharts.com/lib/3/xy.js"></script>
    <script src="../../static/js/TrecEvaluation/trec_eval.js" type="text/javascript"></script>
    <script>
        var precision = {{ precision|tojson }};
        var recall = {{ recall|tojson }};
    </script>
</body>
</html>

IR_Evaluation/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Manual Assessment</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../static/css/common.css">

</head>
<body>
    <br><br><br><br>
    <div class="container">
        <div class="jumbotron">
            <h1 class="panel-title">
                Welcome, User!
            </h1>
            <p>
                <h3>What would you like to do today?</h3>
            </p>
            <br><br>
            <a href="{{ url_for('manual_assessment.assess')}}" methods="get">
                <button class="btn btn-primary">Manual Assessment</button>
            </a>
            <a href="{{ url_for('manual_assessment.store_results')}}" methods="get">
                <button class="btn btn-primary">Store Results</button>
            </a>
            <a href="{{ url_for('trec_eval.trec_evaluation')}}" methods="get">
                <button class="btn btn-primary">TREC Evaluation</button>
            </a>
        </div>
    </div>
</body>
</html>